// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createUser, deleteCurrentUser, getCurrentUser, getCurrentUserLogs, getEpisode, getSeason, getShow, getUserById, getUsers, logEpisode, login, type Options, root, searchShows, updateCurrentUser } from '../sdk.gen';
import type { CreateUserData, CreateUserError, CreateUserResponse, DeleteCurrentUserData, DeleteCurrentUserResponse, GetCurrentUserData, GetCurrentUserLogsData, GetCurrentUserLogsResponse, GetCurrentUserResponse, GetEpisodeData, GetEpisodeError, GetEpisodeResponse, GetSeasonData, GetSeasonError, GetSeasonResponse, GetShowData, GetShowError, GetShowResponse, GetUserByIdData, GetUserByIdError, GetUserByIdResponse, GetUsersData, GetUsersError, GetUsersResponse, LogEpisodeData, LogEpisodeError, LogEpisodeResponse, LoginData, LoginError, LoginResponse, RootData, SearchShowsData, SearchShowsError, SearchShowsResponse, UpdateCurrentUserData, UpdateCurrentUserError, UpdateCurrentUserResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getUsersQueryKey = (options?: Options<GetUsersData>) => createQueryKey('getUsers', options);

/**
 * Get Users
 */
export const getUsersOptions = (options?: Options<GetUsersData>) => queryOptions<GetUsersResponse, GetUsersError, GetUsersResponse, ReturnType<typeof getUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUsersQueryKey(options)
});

/**
 * Create User
 */
export const createUserMutation = (options?: Partial<Options<CreateUserData>>): UseMutationOptions<CreateUserResponse, CreateUserError, Options<CreateUserData>> => {
    const mutationOptions: UseMutationOptions<CreateUserResponse, CreateUserError, Options<CreateUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Current User
 */
export const deleteCurrentUserMutation = (options?: Partial<Options<DeleteCurrentUserData>>): UseMutationOptions<DeleteCurrentUserResponse, DefaultError, Options<DeleteCurrentUserData>> => {
    const mutationOptions: UseMutationOptions<DeleteCurrentUserResponse, DefaultError, Options<DeleteCurrentUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteCurrentUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCurrentUserQueryKey = (options?: Options<GetCurrentUserData>) => createQueryKey('getCurrentUser', options);

/**
 * Get Current User
 */
export const getCurrentUserOptions = (options?: Options<GetCurrentUserData>) => queryOptions<GetCurrentUserResponse, DefaultError, GetCurrentUserResponse, ReturnType<typeof getCurrentUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCurrentUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCurrentUserQueryKey(options)
});

/**
 * Update Current User
 */
export const updateCurrentUserMutation = (options?: Partial<Options<UpdateCurrentUserData>>): UseMutationOptions<UpdateCurrentUserResponse, UpdateCurrentUserError, Options<UpdateCurrentUserData>> => {
    const mutationOptions: UseMutationOptions<UpdateCurrentUserResponse, UpdateCurrentUserError, Options<UpdateCurrentUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateCurrentUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUserByIdQueryKey = (options: Options<GetUserByIdData>) => createQueryKey('getUserById', options);

/**
 * Get User By Id
 */
export const getUserByIdOptions = (options: Options<GetUserByIdData>) => queryOptions<GetUserByIdResponse, GetUserByIdError, GetUserByIdResponse, ReturnType<typeof getUserByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUserById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserByIdQueryKey(options)
});

export const getCurrentUserLogsQueryKey = (options?: Options<GetCurrentUserLogsData>) => createQueryKey('getCurrentUserLogs', options);

/**
 * Get Current User Logs
 */
export const getCurrentUserLogsOptions = (options?: Options<GetCurrentUserLogsData>) => queryOptions<GetCurrentUserLogsResponse, DefaultError, GetCurrentUserLogsResponse, ReturnType<typeof getCurrentUserLogsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCurrentUserLogs({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCurrentUserLogsQueryKey(options)
});

/**
 * Login
 */
export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const searchShowsQueryKey = (options: Options<SearchShowsData>) => createQueryKey('searchShows', options);

/**
 * Search Shows
 */
export const searchShowsOptions = (options: Options<SearchShowsData>) => queryOptions<SearchShowsResponse, SearchShowsError, SearchShowsResponse, ReturnType<typeof searchShowsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await searchShows({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: searchShowsQueryKey(options)
});

export const getShowQueryKey = (options: Options<GetShowData>) => createQueryKey('getShow', options);

/**
 * Get Show
 */
export const getShowOptions = (options: Options<GetShowData>) => queryOptions<GetShowResponse, GetShowError, GetShowResponse, ReturnType<typeof getShowQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getShow({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getShowQueryKey(options)
});

export const getSeasonQueryKey = (options: Options<GetSeasonData>) => createQueryKey('getSeason', options);

/**
 * Get Season
 */
export const getSeasonOptions = (options: Options<GetSeasonData>) => queryOptions<GetSeasonResponse, GetSeasonError, GetSeasonResponse, ReturnType<typeof getSeasonQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSeason({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSeasonQueryKey(options)
});

export const getEpisodeQueryKey = (options: Options<GetEpisodeData>) => createQueryKey('getEpisode', options);

/**
 * Get Episode
 */
export const getEpisodeOptions = (options: Options<GetEpisodeData>) => queryOptions<GetEpisodeResponse, GetEpisodeError, GetEpisodeResponse, ReturnType<typeof getEpisodeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getEpisode({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getEpisodeQueryKey(options)
});

/**
 * Log Episode
 */
export const logEpisodeMutation = (options?: Partial<Options<LogEpisodeData>>): UseMutationOptions<LogEpisodeResponse, LogEpisodeError, Options<LogEpisodeData>> => {
    const mutationOptions: UseMutationOptions<LogEpisodeResponse, LogEpisodeError, Options<LogEpisodeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logEpisode({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const rootQueryKey = (options?: Options<RootData>) => createQueryKey('root', options);

/**
 * Root
 */
export const rootOptions = (options?: Options<RootData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof rootQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await root({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: rootQueryKey(options)
});
