// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, type Options as Options2, type RequestResult, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { CreateUserData, CreateUserErrors, CreateUserResponses, DeleteCurrentUserData, DeleteCurrentUserResponses, GetCurrentUserData, GetCurrentUserLogsData, GetCurrentUserLogsResponses, GetCurrentUserResponses, GetEpisodeData, GetEpisodeErrors, GetEpisodeResponses, GetSeasonData, GetSeasonErrors, GetSeasonResponses, GetShowData, GetShowErrors, GetShowResponses, GetUserByIdData, GetUserByIdErrors, GetUserByIdResponses, GetUsersData, GetUsersErrors, GetUsersResponses, LogEpisodeData, LogEpisodeErrors, LogEpisodeResponses, LoginData, LoginErrors, LoginResponses, RootData, RootResponses, SearchShowsData, SearchShowsErrors, SearchShowsResponses, UpdateCurrentUserData, UpdateCurrentUserErrors, UpdateCurrentUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get Users
 */
export const getUsers = <ThrowOnError extends boolean = false>(options?: Options<GetUsersData, ThrowOnError>): RequestResult<GetUsersResponses, GetUsersErrors, ThrowOnError> => (options?.client ?? client).get<GetUsersResponses, GetUsersErrors, ThrowOnError>({ url: '/users', ...options });

/**
 * Create User
 */
export const createUser = <ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>): RequestResult<CreateUserResponses, CreateUserErrors, ThrowOnError> => (options.client ?? client).post<CreateUserResponses, CreateUserErrors, ThrowOnError>({
    url: '/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Current User
 */
export const deleteCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<DeleteCurrentUserData, ThrowOnError>): RequestResult<DeleteCurrentUserResponses, unknown, ThrowOnError> => (options?.client ?? client).delete<DeleteCurrentUserResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me',
    ...options
});

/**
 * Get Current User
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>): RequestResult<GetCurrentUserResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetCurrentUserResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me',
    ...options
});

/**
 * Update Current User
 */
export const updateCurrentUser = <ThrowOnError extends boolean = false>(options: Options<UpdateCurrentUserData, ThrowOnError>): RequestResult<UpdateCurrentUserResponses, UpdateCurrentUserErrors, ThrowOnError> => (options.client ?? client).put<UpdateCurrentUserResponses, UpdateCurrentUserErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get User By Id
 */
export const getUserById = <ThrowOnError extends boolean = false>(options: Options<GetUserByIdData, ThrowOnError>): RequestResult<GetUserByIdResponses, GetUserByIdErrors, ThrowOnError> => (options.client ?? client).get<GetUserByIdResponses, GetUserByIdErrors, ThrowOnError>({ url: '/users/{user_id}', ...options });

/**
 * Get Current User Logs
 */
export const getCurrentUserLogs = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserLogsData, ThrowOnError>): RequestResult<GetCurrentUserLogsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetCurrentUserLogsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/logs',
    ...options
});

/**
 * Login
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, LoginErrors, ThrowOnError> => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    url: '/sessions',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * Search Shows
 */
export const searchShows = <ThrowOnError extends boolean = false>(options: Options<SearchShowsData, ThrowOnError>): RequestResult<SearchShowsResponses, SearchShowsErrors, ThrowOnError> => (options.client ?? client).get<SearchShowsResponses, SearchShowsErrors, ThrowOnError>({ url: '/shows', ...options });

/**
 * Get Show
 */
export const getShow = <ThrowOnError extends boolean = false>(options: Options<GetShowData, ThrowOnError>): RequestResult<GetShowResponses, GetShowErrors, ThrowOnError> => (options.client ?? client).get<GetShowResponses, GetShowErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/shows/{show_id}',
    ...options
});

/**
 * Get Season
 */
export const getSeason = <ThrowOnError extends boolean = false>(options: Options<GetSeasonData, ThrowOnError>): RequestResult<GetSeasonResponses, GetSeasonErrors, ThrowOnError> => (options.client ?? client).get<GetSeasonResponses, GetSeasonErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/seasons/{season_id}',
    ...options
});

/**
 * Get Episode
 */
export const getEpisode = <ThrowOnError extends boolean = false>(options: Options<GetEpisodeData, ThrowOnError>): RequestResult<GetEpisodeResponses, GetEpisodeErrors, ThrowOnError> => (options.client ?? client).get<GetEpisodeResponses, GetEpisodeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/episodes/{episode_id}',
    ...options
});

/**
 * Log Episode
 */
export const logEpisode = <ThrowOnError extends boolean = false>(options: Options<LogEpisodeData, ThrowOnError>): RequestResult<LogEpisodeResponses, LogEpisodeErrors, ThrowOnError> => (options.client ?? client).post<LogEpisodeResponses, LogEpisodeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/episodes/{episode_id}/logs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Root
 */
export const root = <ThrowOnError extends boolean = false>(options?: Options<RootData, ThrowOnError>): RequestResult<RootResponses, unknown, ThrowOnError> => (options?.client ?? client).get<RootResponses, unknown, ThrowOnError>({ url: '/', ...options });
