// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Actor
 */
export type Actor = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Profile Path
     */
    profile_path: string | null;
};

/**
 * Body_login
 */
export type BodyLogin = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CastMemberResponse
 */
export type CastMemberResponse = {
    /**
     * Character
     */
    character: string | null;
    /**
     * Id
     */
    readonly id: number;
    /**
     * Name
     */
    readonly name: string;
    /**
     * Profile Path
     */
    readonly profile_path: string | null;
};

/**
 * Creator
 */
export type Creator = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Profile Path
     */
    profile_path: string | null;
};

/**
 * EpisodeLogResponse
 */
export type EpisodeLogResponse = {
    /**
     * Episode Id
     */
    episode_id: number;
    /**
     * Logged At
     */
    logged_at: string | null;
    /**
     * Episode Name
     */
    episode_name: string;
};

/**
 * EpisodeResponse
 */
export type EpisodeResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Episode Number
     */
    episode_number: number;
    /**
     * Overview
     */
    overview: string | null;
    /**
     * Runtime
     */
    runtime: number | null;
    /**
     * Air Date
     */
    air_date: string | null;
    /**
     * Vote Average
     */
    vote_average: number | null;
    /**
     * Guest Stars
     */
    guest_stars: Array<CastMemberResponse>;
    /**
     * Still Path
     */
    still_path: string | null;
    /**
     * Season Id
     */
    season_id: number;
    /**
     * Is Logged
     */
    is_logged: boolean;
};

/**
 * EpisodeSummary
 */
export type EpisodeSummary = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string | null;
    /**
     * Is Logged
     */
    is_logged: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * SeasonResponse
 */
export type SeasonResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Season Number
     */
    season_number: number;
    /**
     * Overview
     */
    overview: string | null;
    /**
     * Air Date
     */
    air_date: string | null;
    /**
     * Vote Average
     */
    vote_average: number | null;
    /**
     * Cast
     */
    cast: Array<CastMemberResponse>;
    /**
     * Poster Path
     */
    poster_path: string | null;
    /**
     * Show Id
     */
    show_id: number;
    /**
     * Episodes With Progress
     */
    episodes_with_progress: Array<EpisodeSummary>;
};

/**
 * SeasonSummary
 */
export type SeasonSummary = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string | null;
    /**
     * Logged Eps
     */
    logged_eps: number;
    /**
     * Total Eps
     */
    total_eps: number;
};

/**
 * ShowResponse
 */
export type ShowResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: string | null;
    /**
     * Overview
     */
    overview: string | null;
    /**
     * Genres
     */
    genres: Array<string>;
    /**
     * First Air Date
     */
    first_air_date: string | null;
    /**
     * Last Air Date
     */
    last_air_date: string | null;
    /**
     * Vote Average
     */
    vote_average: number | null;
    /**
     * Creators
     */
    creators: Array<Creator>;
    /**
     * Poster Path
     */
    poster_path: string | null;
    /**
     * Backdrop Path
     */
    backdrop_path: string | null;
    /**
     * Seasons With Progress
     */
    seasons_with_progress: Array<SeasonSummary> | null;
    /**
     * Last Updated
     */
    last_updated: string;
};

/**
 * ShowSearchResult
 */
export type ShowSearchResult = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: number;
    /**
     * Poster Path
     */
    poster_path?: string | null;
    /**
     * Year
     */
    year?: number | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserLogSummary
 */
export type UserLogSummary = {
    /**
     * Logged At
     */
    logged_at: string;
    /**
     * Episode Name
     */
    episode_name: string;
    /**
     * Season Name
     */
    season_name: string;
    /**
     * Show Name
     */
    show_name: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Username
     */
    username: string;
    /**
     * Id
     */
    id: number;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Username
     */
    username: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * CastMemberResponse
 */
export type CastMemberResponseWritable = {
    /**
     * Character
     */
    character: string | null;
};

/**
 * EpisodeResponse
 */
export type EpisodeResponseWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Episode Number
     */
    episode_number: number;
    /**
     * Overview
     */
    overview: string | null;
    /**
     * Runtime
     */
    runtime: number | null;
    /**
     * Air Date
     */
    air_date: string | null;
    /**
     * Vote Average
     */
    vote_average: number | null;
    /**
     * Guest Stars
     */
    guest_stars: Array<CastMemberResponseWritable>;
    /**
     * Still Path
     */
    still_path: string | null;
    /**
     * Season Id
     */
    season_id: number;
    /**
     * Is Logged
     */
    is_logged: boolean;
};

/**
 * SeasonResponse
 */
export type SeasonResponseWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Season Number
     */
    season_number: number;
    /**
     * Overview
     */
    overview: string | null;
    /**
     * Air Date
     */
    air_date: string | null;
    /**
     * Vote Average
     */
    vote_average: number | null;
    /**
     * Cast
     */
    cast: Array<CastMemberResponseWritable>;
    /**
     * Poster Path
     */
    poster_path: string | null;
    /**
     * Show Id
     */
    show_id: number;
    /**
     * Episodes With Progress
     */
    episodes_with_progress: Array<EpisodeSummary>;
};

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Username
         *
         * A username or no argument for all users
         */
        username?: string | null;
    };
    url: '/users';
};

export type GetUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersError = GetUsersErrors[keyof GetUsersErrors];

export type GetUsersResponses = {
    /**
     * Response Get Users
     *
     * Successful Response
     */
    200: UserResponse | Array<UserResponse>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type CreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/users';
};

export type CreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type DeleteCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type DeleteCurrentUserResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCurrentUserResponse = DeleteCurrentUserResponses[keyof DeleteCurrentUserResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type UpdateCurrentUserData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UpdateCurrentUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCurrentUserError = UpdateCurrentUserErrors[keyof UpdateCurrentUserErrors];

export type UpdateCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type UpdateCurrentUserResponse = UpdateCurrentUserResponses[keyof UpdateCurrentUserResponses];

export type GetUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         *
         * A user ID
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type GetUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserByIdError = GetUserByIdErrors[keyof GetUserByIdErrors];

export type GetUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type GetCurrentUserLogsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/logs';
};

export type GetCurrentUserLogsResponses = {
    /**
     * Response Get Current User Logs
     *
     * Successful Response
     */
    200: Array<UserLogSummary>;
};

export type GetCurrentUserLogsResponse = GetCurrentUserLogsResponses[keyof GetCurrentUserLogsResponses];

export type LoginData = {
    body: BodyLogin;
    path?: never;
    query?: never;
    url: '/sessions';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type SearchShowsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Name
         *
         * A title to search
         */
        name: string;
    };
    url: '/shows';
};

export type SearchShowsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchShowsError = SearchShowsErrors[keyof SearchShowsErrors];

export type SearchShowsResponses = {
    /**
     * Response Search Shows
     *
     * Successful Response
     */
    200: Array<ShowSearchResult>;
};

export type SearchShowsResponse = SearchShowsResponses[keyof SearchShowsResponses];

export type GetShowData = {
    body?: never;
    path: {
        /**
         * Show Id
         */
        show_id: number;
    };
    query?: never;
    url: '/shows/{show_id}';
};

export type GetShowErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetShowError = GetShowErrors[keyof GetShowErrors];

export type GetShowResponses = {
    /**
     * Successful Response
     */
    200: ShowResponse;
};

export type GetShowResponse = GetShowResponses[keyof GetShowResponses];

export type GetSeasonData = {
    body?: never;
    path: {
        /**
         * Season Id
         */
        season_id: number;
    };
    query?: {
        /**
         * View
         */
        view?: 'full' | 'progress' | null;
    };
    url: '/seasons/{season_id}';
};

export type GetSeasonErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSeasonError = GetSeasonErrors[keyof GetSeasonErrors];

export type GetSeasonResponses = {
    /**
     * Response Get Season
     *
     * Successful Response
     */
    200: SeasonResponse | Array<EpisodeSummary>;
};

export type GetSeasonResponse = GetSeasonResponses[keyof GetSeasonResponses];

export type GetEpisodeData = {
    body?: never;
    path: {
        /**
         * Episode Id
         */
        episode_id: number;
    };
    query?: never;
    url: '/episodes/{episode_id}';
};

export type GetEpisodeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEpisodeError = GetEpisodeErrors[keyof GetEpisodeErrors];

export type GetEpisodeResponses = {
    /**
     * Successful Response
     */
    200: EpisodeResponse;
};

export type GetEpisodeResponse = GetEpisodeResponses[keyof GetEpisodeResponses];

export type LogEpisodeData = {
    /**
     * Logged At
     */
    body?: string | null;
    path: {
        /**
         * Episode Id
         */
        episode_id: number;
    };
    query?: never;
    url: '/episodes/{episode_id}/logs';
};

export type LogEpisodeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogEpisodeError = LogEpisodeErrors[keyof LogEpisodeErrors];

export type LogEpisodeResponses = {
    /**
     * Successful Response
     */
    200: EpisodeLogResponse;
};

export type LogEpisodeResponse = LogEpisodeResponses[keyof LogEpisodeResponses];

export type RootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
