"""add shows, seasons, episodes

Revision ID: 14958744acf9
Revises: d82eb4ef3939
Create Date: 2026-09-25 14:56:03.701611

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '14958744acf9'
down_revision: str | Sequence[str] | None = 'd82eb4ef3939'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'actors',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('profile_path', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'creators',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('profile_path', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'shows',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('overview', sa.String(), nullable=True),
        sa.Column('genres', sa.ARRAY(sa.String()), nullable=False),
        sa.Column('first_air_date', sa.Date(), nullable=True),
        sa.Column('last_air_date', sa.Date(), nullable=True),
        sa.Column('vote_average', sa.Float(), nullable=True),
        sa.Column('poster_path', sa.String(), nullable=True),
        sa.Column('backdrop_path', sa.String(), nullable=True),
        sa.Column(
            'last_updated',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'creator_credits',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('creator_id', sa.Integer(), nullable=False),
        sa.Column('show_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['creator_id'],
            ['creators.id'],
        ),
        sa.ForeignKeyConstraint(
            ['show_id'],
            ['shows.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'seasons',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('show_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('season_number', sa.Integer(), nullable=False),
        sa.Column('overview', sa.String(), nullable=True),
        sa.Column('air_date', sa.Date(), nullable=True),
        sa.Column('vote_average', sa.Float(), nullable=True),
        sa.Column('poster_path', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_unique_constraint(
        'uq_show_season_number', 'seasons', ['show_id', 'season_number']
    )
    op.create_table(
        'episodes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('season_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('episode_number', sa.Integer(), nullable=False),
        sa.Column('overview', sa.String(), nullable=True),
        sa.Column('runtime', sa.Integer(), nullable=True),
        sa.Column('air_date', sa.Date(), nullable=True),
        sa.Column('vote_average', sa.Float(), nullable=True),
        sa.Column('still_path', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_unique_constraint(
        'uq_season_episode_number', 'episodes', ['season_id', 'episode_number']
    )
    op.create_table(
        'roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('actor_id', sa.Integer(), nullable=False),
        sa.Column('character', sa.String(), nullable=True),
        sa.Column('season_id', sa.Integer(), nullable=True),
        sa.Column('episode_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episodes')
    op.drop_table('seasons')
    op.drop_table('shows')
    # ### end Alembic commands ###
