/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as EpisodesIdRouteImport } from './routes/episodes.$id'
import { Route as SeasonsIdRouteImport } from './routes/seasons.$id'
import { Route as ShowsIdRouteImport } from './routes/shows.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesIdRoute = EpisodesIdRouteImport.update({
  id: '/episodes/$id',
  path: '/episodes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsIdRoute = SeasonsIdRouteImport.update({
  id: '/seasons/$id',
  path: '/seasons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsIdRoute = ShowsIdRouteImport.update({
  id: '/shows/$id',
  path: '/shows/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/episodes/$id': typeof EpisodesIdRoute
  '/seasons/$id': typeof SeasonsIdRoute
  '/shows/$id': typeof ShowsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/episodes/$id': typeof EpisodesIdRoute
  '/seasons/$id': typeof SeasonsIdRoute
  '/shows/$id': typeof ShowsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/episodes/$id': typeof EpisodesIdRoute
  '/seasons/$id': typeof SeasonsIdRoute
  '/shows/$id': typeof ShowsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/search'
    | '/signup'
    | '/episodes/$id'
    | '/seasons/$id'
    | '/shows/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/search'
    | '/signup'
    | '/episodes/$id'
    | '/seasons/$id'
    | '/shows/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/search'
    | '/signup'
    | '/episodes/$id'
    | '/seasons/$id'
    | '/shows/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  EpisodesIdRoute: typeof EpisodesIdRoute
  SeasonsIdRoute: typeof SeasonsIdRoute
  ShowsIdRoute: typeof ShowsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/$id': {
      id: '/episodes/$id'
      path: '/episodes/$id'
      fullPath: '/episodes/$id'
      preLoaderRoute: typeof EpisodesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons/$id': {
      id: '/seasons/$id'
      path: '/seasons/$id'
      fullPath: '/seasons/$id'
      preLoaderRoute: typeof SeasonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$id': {
      id: '/shows/$id'
      path: '/shows/$id'
      fullPath: '/shows/$id'
      preLoaderRoute: typeof ShowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  EpisodesIdRoute: EpisodesIdRoute,
  SeasonsIdRoute: SeasonsIdRoute,
  ShowsIdRoute: ShowsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
